/*
Copyright 2023 The Kubernetes Authors.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/api/core/v1"
)

// VolumeClaimPolicyApplyConfiguration represents a declarative configuration of the VolumeClaimPolicy type for use
// with apply.
type VolumeClaimPolicyApplyConfiguration struct {
	Templates       []v1.PersistentVolumeClaim               `json:"templates,omitempty"`
	RetentionPolicy *VolumeRetentionPolicyApplyConfiguration `json:"retentionPolicy,omitempty"`
}

// VolumeClaimPolicyApplyConfiguration constructs a declarative configuration of the VolumeClaimPolicy type for use with
// apply.
func VolumeClaimPolicy() *VolumeClaimPolicyApplyConfiguration {
	return &VolumeClaimPolicyApplyConfiguration{}
}

// WithTemplates adds the given value to the Templates field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Templates field.
func (b *VolumeClaimPolicyApplyConfiguration) WithTemplates(values ...v1.PersistentVolumeClaim) *VolumeClaimPolicyApplyConfiguration {
	for i := range values {
		b.Templates = append(b.Templates, values[i])
	}
	return b
}

// WithRetentionPolicy sets the RetentionPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetentionPolicy field is set to the value of the last call.
func (b *VolumeClaimPolicyApplyConfiguration) WithRetentionPolicy(value *VolumeRetentionPolicyApplyConfiguration) *VolumeClaimPolicyApplyConfiguration {
	b.RetentionPolicy = value
	return b
}
